#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.9pre on Wed Sep 18 23:31:09 2019
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class LoginFrame(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: LoginFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle("dialog")
        
        vbox_main = wx.BoxSizer(wx.VERTICAL)
        
        hbox_user = wx.BoxSizer(wx.HORIZONTAL)
        vbox_main.Add(hbox_user, 0, wx.ALL | wx.EXPAND, 5)
        
        bitmap_1 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("C:\\Users\\Administrator\\PycharmProjects\\jira_picker\\icons\\icons8-account-32.png", wx.BITMAP_TYPE_ANY))
        hbox_user.Add(bitmap_1, 0, 0, 0)
        
        self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.text_ctrl_1.SetMinSize((-1, 32))
        hbox_user.Add(self.text_ctrl_1, 1, 0, 0)
        
        hbox_password = wx.BoxSizer(wx.HORIZONTAL)
        vbox_main.Add(hbox_password, 0, wx.ALL | wx.EXPAND, 5)
        
        bitmap_2 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("C:\\Users\\Administrator\\PycharmProjects\\jira_picker\\icons\\icons8-lock-32.png", wx.BITMAP_TYPE_ANY))
        hbox_password.Add(bitmap_2, 0, 0, 0)
        
        self.text_ctrl_2 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.text_ctrl_2.SetMinSize((-1, 32))
        hbox_password.Add(self.text_ctrl_2, 1, 0, 0)
        
        self.btn_login = wx.Button(self, wx.ID_ANY, "LOGIN", style=wx.BORDER_NONE)
        self.btn_login.SetMinSize((-1, 32))
        vbox_main.Add(self.btn_login, 0, wx.ALL | wx.EXPAND, 5)
        
        hbox_remember = wx.BoxSizer(wx.HORIZONTAL)
        vbox_main.Add(hbox_remember, 0, wx.ALL | wx.EXPAND, 5)
        
        self.ckbox_remember_me = wx.CheckBox(self, wx.ID_ANY, "Remember me")
        self.ckbox_remember_me.SetMinSize((-1, 32))
        hbox_remember.Add(self.ckbox_remember_me, 1, 0, 0)
        
        self.btn_forgot_pass = wx.Button(self, wx.ID_ANY, "Forgot your password?", style=wx.BORDER_NONE)
        self.btn_forgot_pass.SetMinSize((-1, 32))
        hbox_remember.Add(self.btn_forgot_pass, 1, 0, 0)
        
        self.btn_register = wx.Button(self, wx.ID_ANY, "REGISTER")
        self.btn_register.SetMinSize((-1, 32))
        vbox_main.Add(self.btn_register, 0, wx.ALL | wx.EXPAND, 5)
        
        self.SetSizer(vbox_main)
        vbox_main.Fit(self)
        
        self.Layout()
        # end wxGlade

# end of class LoginFrame

class MyApp(wx.App):
    def OnInit(self):
        self.Login = LoginFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.Login)
        self.Login.ShowModal()
        self.Login.Destroy()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
