#----------------------------------------------------------------------
# This file was generated by img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

jira_32px = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAhCAYAAAC4JqlRAAABGElEQVRYhcXXPwtBYRQG8PPN"
    "DMpgM8hik5LZoCxGi8WmlA9A2SxIyv8w+DcpxWbzCRh4dLtc3nPec6+nnvG8v+PWvb2I7BIm"
    "oqHlGeJEiej27CJoPO7AA18i+QFHN37jmS84uvILzxrg6E4bzzNwdK6FFwU4urXFyxY4OpHi"
    "VQVc/HbUFHF0aoo3fMDR/S+8xTwQ4cyMvPCBEJcs8fZ29C1xyRJjDK2VcMkSa+6AaVhnLv/4"
    "BF6XmY7SEpwz2u7hnuUSnNmu1y/gfoQkeNMLR7gfI07HZJi6D/jZFEcqiviViyMlBfwkxZGC"
    "BX6xxZGcAD9o4UiagR+1cSRlgKtfyd1J/BNHYh9wtf8Bpok48FnQOBKix1VOnDvrXfbOq3K7"
    "7AAAAABJRU5ErkJggg==")

