#----------------------------------------------------------------------
# This file was generated by img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

jira_32px = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAhCAYAAAC4JqlRAAABGElEQVRYhcXXPwtBYRQG8PPN"
    "DMpgM8hik5LZoCxGi8WmlA9A2SxIyv8w+DcpxWbzCRh4dLtc3nPec6+nnvG8v+PWvb2I7BIm"
    "oqHlGeJEiej27CJoPO7AA18i+QFHN37jmS84uvILzxrg6E4bzzNwdK6FFwU4urXFyxY4OpHi"
    "VQVc/HbUFHF0aoo3fMDR/S+8xTwQ4cyMvPCBEJcs8fZ29C1xyRJjDK2VcMkSa+6AaVhnLv/4"
    "BF6XmY7SEpwz2u7hnuUSnNmu1y/gfoQkeNMLR7gfI07HZJi6D/jZFEcqiviViyMlBfwkxZGC"
    "BX6xxZGcAD9o4UiagR+1cSRlgKtfyd1J/BNHYh9wtf8Bpok48FnQOBKix1VOnDvrXfbOq3K7"
    "7AAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
icons8_account_32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAAmJLR0QA/4ePzL8AAAEqSURB"
    "VEjH3ZW7SgNBGEYPaZIicQW7RNwmLyAh0SeIms4uzaqgheJjCHkDBWOvwfSaWkynqOADCGKh"
    "JJ0XDISxcF2c7Az8f5v5yuGcYS4fA1M8AvbocEWPA+b0eIMBJskTi2Q0eI3RP/w3j4RywXUK"
    "NxgupHjoxA1jSjLBukdgWJUJtryCTZlgzStoyAQF3p34BzMywRJjzyHWZIIV7xbqMkGOByd+"
    "T07eg+8UPmJW85iPUoJDXZkK3Fn4LXltH6uWoKovdMUSVPSCyBJEekFIL8EvWZBf4AZd+nFx"
    "yzRpUgZgnj5dIgI/XKLNV7zmgG2yyUyWHYbxzCfHFF34Mm8TNz/klBYtzhL4L6/pVgS8eBvg"
    "yvPkVvZVuMGwawvO1YKOLTjhRpn21HyhP498OeLQS5STAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
icons8_lock_32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAAmJLR0QA/4ePzL8AAAEASURB"
    "VEiJ5cy9SkJxHMfhp4J0K6jR1UEcDxQUONRee12A0NBUDV2FtEkvQ0Hh4BKBOjjWJdQlhE1q"
    "s+c0NWjaeQGX+v+2/5fPw5xfXj5ruulOTyTy7tZGujjnUqitqqKiqiNUt5w0X/KkZ2fsb9eH"
    "R4vJgHN9pR+/ZUNnSfJVA0dTl2N9K/HAoaHc1CXv00E8cKE9c+uoxQMNNzO3G414oKk+c6tr"
    "zhFYUBQIdDUFM66pKxAoTgMeRCnufjIvpMojkcI4UEoNlP4J8GrPvrfswBbYzg6UQTk7cAWu"
    "swMt0MoOPIOX7ECopibMDvx2fw9YN0qVj6yZeKcGifO+k+/sCzFu4Ic9y2dOAAAAAElFTkSu"
    "QmCC")

#----------------------------------------------------------------------
icons8_name_64 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAABmJLR0QA/wD/AP+gvaeTAAAH"
    "e0lEQVR42u1aaWwTVxBG/dHrRy+prfqvoKp/+7v/kOKE+IKAd0sOrrRSadWqxCSUqyqUo0mA"
    "AE1VQBy9RClXgQBJOITa4CTkJJQzB7kawpWDHEBiO8l0ZjebfXZC8mzv2o7kkUZaeb3vzcyb"
    "N/PNvDdlSoQipDvNmCG+EWW1xUWZhS0Gs5hrsAjVBrPQiewcZnq+Jb0zC5sNJmGW2Zz4+qRW"
    "evr0RS9Gm8T5qNR5VGoQGXzkATTE2WizbZ7RaHxh0ij+oSi+hMKnId/1Q+lncWuURVxKY4e1"
    "8lEmwYLCNngrEGP9CJakrYaffz8AjqISaGpugd7ex+B2D0hMz43N/0nv9v12AL5KXSV9M4Yh"
    "6qMtNlO4rvpub4ETF30Gh47mQHtHJ/hKbe0dcPDIcUhYuHi0IUzCTtpiYRLg5ryDQlWxAtoS"
    "P4bcM+el1Q2U3G43nMo7B7aEZG9DVETNTHg7pMobzLZp5JasYOlbsqGnpxe0pu6eHti4abuX"
    "EWy3Y6zi1FCu/IjysbPiIe/sBdCbTuefx7nmehgh6J4wvOdH3N5iS4LyyioIFpWWXwbznCSP"
    "7RDUmMAGPFoNEijYVFn1r+R1jBF+CmaqG5nYV7dv6AY4Xg+wFW22pkTmrMvyb/TOF6LgyMoS"
    "ZRJjg+H6DWzA46UHTwF2XgOwXxyfd1zF/z7hN8LGzG2sEep03QoGk7hMmWxOfDJ0dfdwCVnz"
    "CGBl8cTKK7yyCOAWJ3SgjOOVIlN0w/YsvKU8z0N3MCMuL1SVS3MAHKkDqOvC1OaUuRYNdKhW"
    "fqf872v8poUzm+acPuMBm3WpHeTCRkV4PCBnYAhdtFxVip7vj+PerY8B1pep/99QJo8xEblc"
    "Lk/EaBITdYj8UlUnTXDw6AmulXG0qsp8cwmgo48DAmOsWMVsl4utfF7w5+HjrBfka17PS+Xp"
    "cGHDi+0p0iuKFN3lD2wFd9Tvsjgz7MO2doi2iIoB3AaD+Kp27m8RZyvWpaqOKzjh3l7K7Gfn"
    "IL8B+nF3LRuOGzQGjcVDX9pXjHhBtFmcqV3ulzo58sBU0vJQc4+6itv9AIms9zTzJRvY++t+"
    "dRtYbJu03P+5ysCFxaVcwlR3qgrsuua7AXYxmKGaMyUWFF5iQdFJLaFvrTIwNS5405+iQGal"
    "7wagb5TvKTvwUGNTM+MBQrWWBuhQBuYtdfsG1LxO+7jLya98NxM/KBY4OdsKBMyYTPBQSwM4"
    "lYGpQcFLLPQ9dpvfACfq1e92X+f/jvAAY4D+kBvgeruqSCp6w42Oib8hCJzKIMKazvAwQJsy"
    "MC/+V4iKGzvjzoWIBwbHQHf0E2GFZQxs3nPdt7ih5xbwOQgq1OsCWFfqWeykIyTOawKoeCBz"
    "Pj6nV3j+h2DzE7dvBmho1C8InlYGLnAU+xzRKQBmXeavBrdgBujs9z1z6JYGo01CpjIw9e39"
    "IUKC55rlUveZZTDa9kILdoIH/ZoC9vyiExBiofAXKSsCamWRIa5icDzZALC/WmZ6poDpGgxo"
    "aEm2kcMYi82qmQGMxqRXcFCXhLGx4Ojw46BDb3rwsM2jGCKZdSuH/zj4V9gZ4MDhY2ohZBHy"
    "tG+GmoV4ZYKk5M99PvXpc8uuf7ROLo6oGSqhRMz567Dx8cMVGQDd7ORHfmz+j1/wqWoAky1B"
    "cwOIovg8Dn5fmeTEqXy+Ov2p3O5i8/tEvKJI7hI/4swEJItaBgstuh2nU8NRmUhI+mTcuoBW"
    "8XCdiun9YaolKECOlxW6urphdvwixv3FJbp1hcmybFt8fcbWMYWiZub35aMV2lYlg566R3J7"
    "jDICNT/ISwgC56CyGRWjv9uMuODeM3qJ69KzWPRXq/tlCjqfx4mGlEnpcMLjNHfQs6dHvO8G"
    "QBMngiZITHEg+4rnGN+Vyu88usGM60urbxVignUqvIO9/FBcUu5hgNXDBiBDXGnzL6qTslQ3"
    "KC31tSWe70vKKmHGTPaQVMgO2tmg1Wp9GYNNqTI5HVReKq0YEY7clRqb3c7A0xttj39wrHam"
    "o0xzsYejJEvQ7xHFxMx+iz0ep9U4mXsWhoaGdM335PZeK19LsoTkjkBsbPy7uB1q2H248tsN"
    "0vUWrYmivVfAk5QnGUJ6S8RoFN/Ek5gyVrC4uQvhWE4u9PX1B6w4gRzK82yqU9w+ZCs/5rkh"
    "XlzyvsxEQlMbnQ4tfN77+A3BWxbhMbdCfgzLu4N0Pu99Z0jh5MVLIHvnXqmfUN/YJN35ka/J"
    "uSVARb9RPU8lLVV1TGHj4fJBS3UB3RBFNIbC3tPwouQdGnNS3Ril2kEqoPC6q1JK+8huOpCh"
    "wmZSKT6mV8TFvUaXpVGpDCpV5YvR0gVp93DHuR339U1qY1Enh5oZmtfzEYpQhCKkNa0FeC7F"
    "AfOxrbU8FExzkwwhMwAKscAeQMdHCyYjhMwANHmoDYAtt3kh3QIkgL0AMkLBNHdIt0CEIhSh"
    "CI2RGt/H6NzgR0R3YVDL9B4vrQCmplyE28itOPYHYW+AlAJICyCt9XqPh9E+lcn5ayaFB9CK"
    "+aG80+6A9FEGcMA0fFeHXGP/G96L7DGN6X8foWMdPJAgGQAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
icons8_subscription_64 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAQAAAAAYLlVAAAAAmJLR0QA/4ePzL8AAAMESURB"
    "VGje7ZhLSFRRGMd/PiqMHmoalaFUEL0N2hQkaYQgvVCbQItqJT0WQrhpUQ0F4SKCoZW0Smox"
    "2kISolVEtKiIUUjoASEtxqLCTMkwdU6LyTvnXO/c99UW9zubGe75vv9v7v0ecy6EFlpooWXs"
    "EL0MIXxe37hsRzyHO75LZ9YJa4CzAcoL7lrJ5zESKMBVK4Ctgcr3UWgF0Chtj/i8asi3zoDj"
    "EsC8WAjwnwNs56iPSVnHKicA1Qz4XpbTdOshsgGUMxpIZ5jmkt07sIHHvst/oMZZDkT44pv4"
    "H9pZ5LwKCokx7YP8c7a4L8NdvPYkPkIruUrEJVYAbVQqDvm0MuZSvpe1SqwKHhGxAuhikhhL"
    "FccyHjgWH6JRiZFLC6MIOwACQZJjuodxmE+2xVN0sEzx3sFLbe7aAkjfwAolyGLambIh/4bd"
    "il8BUSakwW8bQPCLKAuUYDt5YSr+mygLFY99vFN2OAIQCPp1vyeXFn5mkX/GJmVvER2kdHsc"
    "AwhSdLJCCbyazlm7fswquAhfDSBdAAgEnzmlS8r9vFcKrky5ui5rM3cJIBA80d3gmeRKUu+g"
    "c3gAEIwT1fX0bVyRextQySvTNPUEkJ5qB7I27gLambTw9wyQTspSA/lqJSsCBEgfPs+QI3mV"
    "cm/WnkFiXKCZi3RLOeETgEDwlM0A5HCa77prSZqVoizi5r/R7iOAYIL73DBIuj7WGDyig4z7"
    "DWC8kobyAE1zA9BkchR4GDzAoPLsN1JLsfR9T/AAMSnWdVIIhtkrjbKqoAHOSb9+ZhImpPgr"
    "Mx+PSFPcD4B03ZdrkRq0K1NSfKl7lGgnoB7PAPq6T49jy3/dNQwwTo/SWN0AGNe9DQAj68Kv"
    "up8zgGx17xIg7rHuG7R3AreUGZh5U1BsDnDbc91bLbkvGFi9Q4DzBnVvtRJmAHn0OwI4qXnW"
    "Ojiymtp6PjoAaNP8ihm26RO3SsTlXOOtdJwyW3ITqyJheXgbI04Jc2IuyzAECAH8szop8+fF"
    "Mn0hzjxZFQlGjOr+L8jn+9JbjLxJAAAAAElFTkSuQmCC")

